name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [win, linux, osx]
        architecture: [x64, arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0
    - name: Build
      run: dotnet publish -c Release -r ${{ matrix.os }}-${{ matrix.architecture }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.architecture }}
        path: ./bin/Release/net8.0/${{ matrix.os }}-${{ matrix.architecture }}/publish/BmwDiscovery*
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      if: matrix.os == 'linux' && matrix.architecture == 'x64'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker Image
      run: docker build -f ./Dockerfile -t docker.io/hartimcwildfly/bmw-zgw-discovery ./bin/Release/net8.0/${{ matrix.os }}-${{ matrix.architecture }}/publish/ && docker push docker.io/hartimcwildfly/bmw-zgw-discovery
      if: matrix.os == 'linux' && matrix.architecture == 'x64'
