name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [win, linux, osx]
        architecture: [x64, arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet publish -c Release -r ${{ matrix.os }}-${{ matrix.architecture }} --output artifact
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        path: ./artifact/BmwDiscovery*